services:
  - type: web
    name: digit-recognition
    env: python
    buildCommand: pip install -r requirements.txt && python model/train.py
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
